### ISSUE TITLE
Circular import error with LDPC module

### ISSUE THREAD

**Issue by Ima96** [oscarhiggott/BeliefMatching#1]
Hi!

I was trying to import the *beliefmatching* module to use the *detector_error_model_to_check_matrices* routine, but it seems that it has a circular import error with the LDPC dependency package. I am not sure if this could be resolved in this repository or if it should be fixed in the LDPC repository, but since the *beliefmatching* module is not working for me and LDPC seems fine I decided to post the issue here.

### Steps to reproduce
The steps I follow are the following:
1. `python3 -m venv .venv`.
2. `source .venv/bin/activate`.
3. `python -m pip install beliefmatching`.
4. `python belief.py` where *belief.py* is the first example given in the readme.

The final output for the python command results in the following:
```bash
$ python belief.py
Traceback (most recent call last):
  File "/tmp/python_circular_test/belief.py", line 3, in <module>
    from beliefmatching import BeliefMatching
  File "/tmp/python_circular_test/.venv/lib/python3.11/site-packages/beliefmatching/__init__.py", line 1, in <module>
    from .belief_matching import *
  File "/tmp/python_circular_test/.venv/lib/python3.11/site-packages/beliefmatching/belief_matching.py", line 4, in <module>
    from ldpc import bp_decoder
  File "/tmp/python_circular_test/.venv/lib/python3.11/site-packages/ldpc/__init__.py", line 9, in <module>
    from ldpc.sinter_decoders import SinterBpOsdDecoder
  File "/tmp/python_circular_test/.venv/lib/python3.11/site-packages/ldpc/sinter_decoders/__init__.py", line 1, in <module>
    from ldpc.sinter_decoders.sinter_bposd_decoder import SinterBpOsdDecoder
  File "/tmp/python_circular_test/.venv/lib/python3.11/site-packages/ldpc/sinter_decoders/sinter_bposd_decoder.py", line 6, in <module>
    from beliefmatching import detector_error_model_to_check_matrices
ImportError: cannot import name 'detector_error_model_to_check_matrices' from partially initialized module 'beliefmatching' (most likely due to a circular import) (/tmp/python_circular_test/.venv/lib/python3.11/site-packages/beliefmatching/__init__.py)
```

### Environment
 - OS: Debian 12 (WSL2)
 - Python version: Python 3.11.2

If you need any other information or whatever, I will be glad to help as much as I can!
Thank you very much in advance!

**Comment by oscarhiggott** [comment]
To be honest the easiest thing to do is probably just copy-paste the function where you need it (it's all contained within one file).

I also have an almost identical function  in this package: https://github.com/oscarhiggott/stimbposd. I expect that using that one will avoid the circular dependency.

I'll leave this issue open for now and come back to look for a better fix later, but the above two solutions should work for you in the meantime.

**Comment by Ima96** [comment]
Great, with *stimbposd* module works like a charm! As you said, I will leave the issue open too and you can close it when you fix it/ whenever you consider.

Thank you!

**Comment by quantumgizmos** [comment]
Hi Marc, Oscar

Thanks for pointing this out. I've implemented the fix Oscar suggested. Hopefully it works now!

Cheers,
Joschka

**Comment by Ima96** [comment]
Hi @quantumgizmos 
I have tried with the changes but still fails. I think you missed the import in [sinter_bposd_decoder.py](https://github.com/quantumgizmos/ldpc/blob/main/src_python/ldpc/sinter_decoders/sinter_bposd_decoder.py) file. I tried changing that locally and it seems fine.

Thanks!

**Comment by quantumgizmos** [comment]
Hi @Ima96 

Thanks. I've pushed the fix.

Cheers,
Joschka
